version: '3.8'

services:

  # === DISCOVERY SERVER ===
  discovery-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - movie-network

  # === API GATEWAY ===
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
    networks:
      - movie-network

  # === MOVIE SERVICE ===
  movie-service:
    build: ./movie-service
    container_name: movie-service
    depends_on:
      - movie-db
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://movie-db:5432/moviedb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - movie-network

  movie-db:
    image: postgres:15
    container_name: movie-db
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - movie-network

  # === RATING SERVICE ===
  rating-service:
    build: ./rating-service
    container_name: rating-service
    depends_on:
      - rating-db
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rating-db:5432/ratingdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - movie-network

  rating-db:
    image: postgres:15
    container_name: rating-db
    environment:
      POSTGRES_DB: ratingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    networks:
      - movie-network

  # === REVIEW SERVICE ===
  review-service:
    build: ./review-service
    container_name: review-service
    depends_on:
      - review-db
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://review-db:5432/reviewdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - movie-network

  review-db:
    image: postgres:15
    container_name: review-db
    environment:
      POSTGRES_DB: reviewdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    networks:
      - movie-network

  # === STATS SERVICE ===
  stats-service:
    build: ./stats-service
    container_name: stats-service
    depends_on:
      - stats-db
      - discovery-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/statsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/
    networks:
      - movie-network

  stats-db:
    image: postgres:15
    container_name: stats-db
    environment:
      POSTGRES_DB: statsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    networks:
      - movie-network

networks:
  movie-network:
    driver: bridge
