name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_OWNER: ${{ secrets.DOCKER_USERNAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build each microservice
        run: |
          mvn -f discovery-server/pom.xml clean package -DskipTests
          mvn -f api-gateway/pom.xml clean package -DskipTests
          mvn -f movie-service/pom.xml clean package -DskipTests
          mvn -f rating-service/pom.xml clean package -DskipTests
          mvn -f review-service/pom.xml clean package -DskipTests
          mvn -f stats-service/pom.xml clean package -DskipTests

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t $REGISTRY/${{ secrets.DOCKER_USERNAME }}/discovery-server:latest ./discovery-server
          docker build -t $REGISTRY/${{ secrets.DOCKER_USERNAME }}/api-gateway:latest ./api-gateway
          docker build -t $REGISTRY/${{ secrets.DOCKER_USERNAME }}/movie-service:latest ./movie-service
          docker build -t $REGISTRY/${{ secrets.DOCKER_USERNAME }}/rating-service:latest ./rating-service
          docker build -t $REGISTRY/${{ secrets.DOCKER_USERNAME }}/review-service:latest ./review-service
          docker build -t $REGISTRY/${{ secrets.DOCKER_USERNAME }}/stats-service:latest ./stats-service

          docker push $REGISTRY/${{ secrets.DOCKER_USERNAME }}/discovery-server:latest
          docker push $REGISTRY/${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker push $REGISTRY/${{ secrets.DOCKER_USERNAME }}/movie-service:latest
          docker push $REGISTRY/${{ secrets.DOCKER_USERNAME }}/rating-service:latest
          docker push $REGISTRY/${{ secrets.DOCKER_USERNAME }}/review-service:latest
          docker push $REGISTRY/${{ secrets.DOCKER_USERNAME }}/stats-service:latest
