name: Build & Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Services
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push rating-service
        run: |
          docker build -t $REGISTRY/$IMAGE_PREFIX/rating-service ./rating-service
          docker push $REGISTRY/$IMAGE_PREFIX/rating-service

      - name: Build and Push review-service
        run: |
          docker build -t $REGISTRY/$IMAGE_PREFIX/review-service ./review-service
          docker push $REGISTRY/$IMAGE_PREFIX/review-service

      - name: Build and Push user-service
        run: |
          docker build -t $REGISTRY/$IMAGE_PREFIX/user-service ./user-service
          docker push $REGISTRY/$IMAGE_PREFIX/user-service

      - name: Build and Push stats-service
        run: |
          docker build -t $REGISTRY/$IMAGE_PREFIX/stats-service ./stats-service
          docker push $REGISTRY/$IMAGE_PREFIX/stats-service

      - name: Build and Push api-gateway
        run: |
          docker build -t $REGISTRY/$IMAGE_PREFIX/api-gateway ./api-gateway
          docker push $REGISTRY/$IMAGE_PREFIX/api-gateway

      - name: Build and Push discovery-server
        run: |
          docker build -t $REGISTRY/$IMAGE_PREFIX/discovery-server ./discovery-server
          docker push $REGISTRY/$IMAGE_PREFIX/discovery-server

      # Optional step: Compose test
      # - name: Docker Compose Up (Testing Only)
      #   run: docker-compose -f docker-compose.yml up -d --build
