name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main  # or master, depending on your branch name
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build all services with Maven
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Discovery Server
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/discovery-server:latest ./discovery-server
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/discovery-server:latest

      - name: Build and Push API Gateway
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest ./api-gateway
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest

      - name: Build and Push Movie Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/movie-service:latest ./movie-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/movie-service:latest

      - name: Build and Push Rating Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rating-service:latest ./rating-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rating-service:latest

      - name: Build and Push Review Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/review-service:latest ./review-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/review-service:latest

      - name: Build and Push Stats Service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/stats-service:latest ./stats-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/stats-service:latest
